version: "3"

services:
  gatsbyjs:
    build:
      context: ./Dockerfiles/Gatsbyjs
      args:
        - environment=develop
    ports:
      - 10010:8000
    depends_on:
      - strapi
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network

  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/srv/app
    depends_on:
      - phpmyadmin
    networks:
      - app-network

  db:
    container_name: strapi_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - /var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=strapi
      - PMA_PASSWORD=strapi
    ports:
      - 9050:80
    volumes:
      - /sessions
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge